In [2]:
import pandas as pd
import numpy as np
data = {
 'id_pracownika': [1,2,3,4,5,6,7,8,9,10,
 11,12,13,14,15,16,17,18,19,20,
 3,7,12,18,5, # duplikaty — te same id!
 21,22,23,24,25],
 'imie': ['Anna', 'Bartek', 'CELINA', 'darek', 'Ewa',
 'Filip', 'Gosia', 'HENRYK', 'irena', 'Jan',
 'Kasia', 'Leszek', 'Marta', 'norbert', 'OLGA',
 'Piotr', 'Renata', 'sławek', 'Teresa', 'Urszula',
 'CELINA', 'Gosia', 'Leszek', 'sławek', 'Ewa',
 'Wanda', 'Xawery', 'Yvonne', 'Zbyszek', 'Agata'],
 'dzial': ['Sprzedaz', 'IT', 'HR', 'sprzedaz', 'IT',
 'HR', 'Sprzedaz', 'it', 'HR', 'Sprzedaz',
 'IT', 'HR', 'sprzedaz', 'IT', 'HR',
 'Sprzedaz', 'it', 'HR', 'Sprzedaz', 'IT',
 'HR', 'Sprzedaz', 'HR', 'HR', 'IT',
 'Sprzedaz', 'IT', 'hr', 'Sprzedaz', 'IT'],
 'wynagrodzenie': ['4500', '6200', '3800', '5100', '7500',
 '4200', '5800', '6900', '3500', '4800',
 '7200', '4100', '5500', '6800', '3900',
 '5200', '4700', '6100', '3800', '5400',
 '3800', '5800', '4100', '6100', '7500',
 'brak', '5000', None, '4300', '6600'],
 'data_zatrudnienia': ['2020-03-15', '2019-07-22', '2021-01-10',
 '2018-05-30', '2022-11-01', '2020-08-14',
 '2019-12-05', '2021-06-18', '2017-09-23',
 '2023-02-07', '2020-04-11', '2018-11-28',
 '2022-07-15', '2019-03-19', '2021-10-08',
 '2020-06-25', '2018-08-31', '2022-02-14',
 '2019-05-07', '2021-09-20', '2021-01-10',
 '2019-12-05', '2018-11-28', '2022-02-14',
 '2022-11-01', '2023-01-15', '2022-05-20',
 None, '2020-10-11', '2019-08-03'],
 'ocena_roczna': [4.5, 3.8, None, 4.2, 5.0,
 3.5, 4.7, None, 4.1, 3.9,
 5.0, 4.3, 3.6, None, 4.8,
 3.7, 4.4, 4.9, None, 3.8,
 None, 4.7, 4.3, 4.9, 5.0,
 4.6, None, 4.9, 3.5, 4.1]
}
df = pd.DataFrame(data)
print(f"Wczytano dataset: {df.shape[0]} wierszy, {df.shape[1]} kolumn")
df.head(10)

Wczytano dataset: 30 wierszy, 6 kolumn

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
1,2,Bartek,IT,6200,2019-07-22,3.8
2,3,CELINA,HR,3800,2021-01-10,NaN
3,4,darek,sprzedaz,5100,2018-05-30,4.2
4,5,Ewa,IT,7500,2022-11-01,5.0
5,6,Filip,HR,4200,2020-08-14,3.5
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7
7,8,HENRYK,it,6900,2021-06-18,NaN
8,9,irena,HR,3500,2017-09-23,4.1
9,10,Jan,Sprzedaz,4800,2023-02-07,3.9

## Ćwiczenie 1: Brakujące wartości (20 min)

In [6]:
#1a
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_pracownika      30 non-null     int64
 1   imie               30 non-null     str
 2   dzial              30 non-null     str
 3   wynagrodzenie      29 non-null     str
 4   data_zatrudnienia  29 non-null     str
 5   ocena_roczna       24 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 1.5 KB

In [7]:
df.isna().sum()

id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        1
data_zatrudnienia    1
ocena_roczna         6
dtype: int64

In [9]:
df.isna().sum() / len(df) * 100

id_pracownika         0.000000
imie                  0.000000
dzial                 0.000000
wynagrodzenie         3.333333
data_zatrudnienia     3.333333
ocena_roczna         20.000000
dtype: float64

In [ ]:
df[df.isna().any(axis=1)]

    id_pracownika    imie dzial  wynagrodzenie data_zatrudnienia  ocena_roczna
27             23  Yvonne    hr         5150.0               NaN           4.9

:

In [13]:
#1b
df['wynagrodzenie'].unique()

<StringArray>
['4500', '6200', '3800', '5100', '7500', '4200', '5800', '6900', '3500',
 '4800', '7200', '4100', '5500', '6800', '3900', '5200', '4700', '6100',
 '5400', 'brak', '5000',    nan, '4300', '6600']
Length: 24, dtype: str

In [14]:
df['wynagrodzenie'] = df['wynagrodzenie'].replace('brak', np.nan)

In [15]:
df['wynagrodzenie'] = pd.to_numeric(df['wynagrodzenie'], errors='coerce')

In [16]:
df['wynagrodzenie'].isna().sum()

np.int64(2)

In [18]:
#1c
mediana = df['wynagrodzenie'].median()
print(f"Mediana: {mediana}")

Mediana: 5150.0

In [19]:
df['wynagrodzenie'] = df['wynagrodzenie'].fillna(mediana)

In [20]:
srednia = round(df['ocena_roczna'].mean(), 2)
print(f"Srednia ocena: {srednia}")

Srednia ocena: 4.34

In [21]:
df['ocena_roczna'] = df['ocena_roczna'].fillna(srednia)

In [22]:
df.isna().sum()

id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

In [ ]:
#1d
df_bez_brakow = df.dropna(subset=['data_zatrudnienia'])
print(len(df_bez_brakow))

29

## Ćwiczenie 2: Duplikaty + konwersja typów

In [3]:
# Zacznij od świeżej kopii
df2 = pd.DataFrame(data) # ta sama definicja 'data' co wyżej
# Najpierw napraw wynagrodzenie (tak samo jak w Ćw. 1b)
df2['wynagrodzenie'] = df2['wynagrodzenie'].replace('brak', np.nan)
df2['wynagrodzenie'] = pd.to_numeric(df2['wynagrodzenie'], errors='coerce')

In [8]:
#2a
# 1. Ile pełnych duplikatów (identycznych wierszy) ma dataset?
print(df2.duplicated().sum())

5

In [9]:
# 2. Wyświetl zduplikowane wiersze (te które są kopiami)
print(df2[df2.duplicated()])

    id_pracownika    imie     dzial  wynagrodzenie data_zatrudnienia  \
20              3  CELINA        HR         3800.0        2021-01-10
21              7   Gosia  Sprzedaz         5800.0        2019-12-05
22             12  Leszek        HR         4100.0        2018-11-28
23             18  sławek        HR         6100.0        2022-02-14
24              5     Ewa        IT         7500.0        2022-11-01

    ocena_roczna
20           NaN
21           4.7
22           4.3
23           4.9
24           5.0

In [ ]:
# 3. Czy liczba duplikatów wg id_pracownika jest taka sama?
print(df2.duplicated(subset=['id_pracownika']).sum())
#tak

5

In [12]:
# 4. Wyświetl ile razy pojawia się każde id_pracownika
print(df2['id_pracownika'].value_counts().sort_index())

id_pracownika
1     1
2     1
3     2
4     1
5     2
6     1
7     2
8     1
9     1
10    1
11    1
12    2
13    1
14    1
15    1
16    1
17    1
18    2
19    1
20    1
21    1
22    1
23    1
24    1
25    1
Name: count, dtype: int64

In [14]:
#2b
# 1. Usuń pełne duplikaty i zresetuj indeks
df2 = df2.drop_duplicates().reset_index(drop=True)
# 2. Wyświetl nowy kształt DataFrame
print(df2.shape)

(25, 6)

In [16]:
#2c
# 1. Sprawdź aktualny typ kolumny data_zatrudnienia
print(df2['data_zatrudnienia'].dtype)

str

In [18]:
# 2. Skonwertuj na datetime
df2['data_zatrudnienia'] = pd.to_datetime(df2['data_zatrudnienia'],
errors='coerce')

In [19]:
# 3. Sprawdź nowy typ
print(df2['data_zatrudnienia'].dtype)

datetime64[us]

In [21]:
# 4. Wyodrębnij rok zatrudnienia do nowej kolumny 'rok_zatrudnienia'
df2['rok_zatrudnienia'] = df2['data_zatrudnienia'].dt.year
print(df2['rok_zatrudnienia'].dropna().unique())

[2020. 2019. 2021. 2018. 2022. 2017. 2023.]

In [25]:
#2d
# czyszczenie działu
df2['dzial'] = df2['dzial'].str.strip().str.title()

In [26]:
prac_2021 = df2[df2['rok_zatrudnienia'] >= 2021].shape[0]
print("Liczba pracowników zatrudnionych od 2021:", prac_2021)

Liczba pracowników zatrudnionych od 2021: 10

In [27]:
high_salary = df2[df2['wynagrodzenie'] > 6000].shape[0]
print("Liczba pracowników z wynagrodzeniem > 6000:", high_salary)

Liczba pracowników z wynagrodzeniem > 6000: 7

In [28]:
it_count = df2[df2['dzial'] == 'It'].shape[0]
print("Liczba pracowników w dziale IT:", it_count)

Liczba pracowników w dziale IT: 9

## Ćwiczenie 3: Pełny pipeline czyszczenia

In [29]:
df_clean = pd.DataFrame(data)  # świeży start

# KROK 1: wynagrodzenie → NaN + float
df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].replace('brak', np.nan)
df_clean['wynagrodzenie'] = pd.to_numeric(df_clean['wynagrodzenie'], errors='coerce')

# KROK 2: usunięcie duplikatów + reset indeksu
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

# KROK 3: wypełnienie wynagrodzenia medianą
mediana = df_clean['wynagrodzenie'].median()
df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].fillna(mediana)

# KROK 4: ocena_roczna → średnia
srednia = round(df_clean['ocena_roczna'].mean(), 2)
df_clean['ocena_roczna'] = df_clean['ocena_roczna'].fillna(srednia)

# KROK 5: czyszczenie imion
df_clean['imie'] = df_clean['imie'].str.strip().str.title()

# KROK 6: czyszczenie działów
df_clean['dzial'] = df_clean['dzial'].str.strip().str.title()
df_clean['dzial'] = df_clean['dzial'].str.replace('Hr', 'HR', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('It', 'IT', regex=False)

# KROK 7: konwersja daty
df_clean['data_zatrudnienia'] = pd.to_datetime(
    df_clean['data_zatrudnienia'],
    errors='coerce'
)

# ======================
# WERYFIKACJA
# ======================
print("=== WERYFIKACJA ===")
print(f"Shape: {df_clean.shape}")
print(f"\nDtypes:\n{df_clean.dtypes}")
print(f"\nNaN per kolumna:\n{df_clean.isna().sum()}")
print(f"\nUnikalne działy: {sorted(df_clean['dzial'].unique())}")
print(f"\nPierwsze imiona: {df_clean['imie'].tolist()[:8]}")

=== WERYFIKACJA ===
Shape: (25, 6)

Dtypes:
id_pracownika                 int64
imie                            str
dzial                           str
wynagrodzenie               float64
data_zatrudnienia    datetime64[us]
ocena_roczna                float64
dtype: object

NaN per kolumna:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

Unikalne działy: ['HR', 'IT', 'Sprzedaz']

Pierwsze imiona: ['Anna', 'Bartek', 'Celina', 'Darek', 'Ewa', 'Filip', 'Gosia', 'Henryk']

In [31]:
# Pytanie 1: Jakie jest średnie wynagrodzenie per dział?
df_clean.groupby('dzial')['wynagrodzenie'].mean().round(2)

dzial
HR          4385.71
IT          6255.56
Sprzedaz    4900.00
Name: wynagrodzenie, dtype: float64

In [32]:
# Pytanie 2: Jaka jest średnia ocena per dział?
df_clean.groupby('dzial')['ocena_roczna'].mean().round(2)

dzial
HR          4.39
IT          4.32
Sprzedaz    4.11
Name: ocena_roczna, dtype: float64

In [33]:
# Pytanie 3: Kto jest najlepiej opłacany (top 3)?
df_clean.nlargest(3, 'wynagrodzenie')[['imie', 'dzial', 'wynagrodzenie']]

      imie dzial  wynagrodzenie
4      Ewa    IT         7500.0
10   Kasia    IT         7200.0
7   Henryk    IT         6900.0

In [34]:
# Pytanie 4: Ilu pracowników jest w każdym dziale?
df_clean['dzial'].value_counts()

dzial
Sprzedaz    9
IT          9
HR          7
Name: count, dtype: int64

In [35]:
# Pytanie 1: Ile lat pracuje najdłuższy staż? (dzisiejsza data - najwcześniejsza data zatrudnienia)

najwczesniejsza_data = df_clean['data_zatrudnienia'].min()
staz_lat = (pd.Timestamp.today() - najwczesniejsza_data).days / 365

print(round(staz_lat, 1))

8.6

In [36]:
# Pytanie 2: Kto ma najwyższą ocenę w każdym dziale? (groupby + idxmax)

top_oceny = df_clean.loc[
    df_clean.groupby('dzial')['ocena_roczna'].idxmax(),
    ['imie', 'dzial', 'ocena_roczna']
]

print(top_oceny)

      imie     dzial  ocena_roczna
17  Sławek        HR           4.9
4      Ewa        IT           5.0
6    Gosia  Sprzedaz           4.7

In [37]:
# Pytanie 3: Czy jest korelacja między stażem a wynagrodzeniem?

df_clean['staz_lat'] = (pd.Timestamp.today() - df_clean['data_zatrudnienia']).dt.days / 365

korelacja = df_clean[['staz_lat', 'wynagrodzenie']].corr().iloc[0,1]

print(round(korelacja, 3))

-0.216

## Ćwiczenie 4: Operacje na tekstach + commit

In [38]:
#4a
df_str = pd.DataFrame(data)

In [39]:
# 1. Ile imion jest zapisanych WSZYSTKIMI WIELKIMI LITERAMI?
df_str['imie'].str.isupper().sum()

np.int64(4)

In [40]:
# 2. Ile imion zaczyna się małą literą?
df_str['imie'].str[0].str.islower().sum()

np.int64(5)

In [41]:
# 3. Ile wierszy zawiera 'sprzedaz' w kolumnie dzial (case-insensitive)?
df_str['dzial'].str.lower().str.contains('sprzedaz').sum()

np.int64(10)

In [42]:
#4b
# 1. Czyszczenie imion
df_str['imie'] = df_str['imie'].str.strip().str.title()

In [43]:
# 2. Czyszczenie działów
df_str['dzial'] = df_str['dzial'].str.strip().str.title()
df_str['dzial'] = df_str['dzial'].str.replace('Hr', 'HR', regex=False)
df_str['dzial'] = df_str['dzial'].str.replace('It', 'IT', regex=False)

In [44]:
# 3. Pracownicy z imieniem zaczynającym się na 'A'
df_str[df_str['imie'].str.startswith('A')]

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
29,25,Agata,IT,6600,2019-08-03,4.1

In [45]:
# 4. Długość imienia
df_str['dlugosc_imienia'] = df_str['imie'].str.len()
df_str['dlugosc_imienia'].describe()

count    30.000000
mean      5.333333
std       1.093345
min       3.000000
25%       5.000000
50%       5.500000
75%       6.000000
max       7.000000
Name: dlugosc_imienia, dtype: float64

In [46]:
# 5. Kto ma najdłuższe imię?
df_str.loc[df_str['dlugosc_imienia'].idxmax(), ['imie', 'dlugosc_imienia']]

imie               Norbert
dlugosc_imienia          7
Name: 13, dtype: object

In [47]:
#4c
# 1. IT lub HR
df_str[df_str['dzial'].str.contains('IT|HR')]

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna,dlugosc_imienia
1,2,Bartek,IT,6200,2019-07-22,3.8,6
2,3,Celina,HR,3800,2021-01-10,NaN,6
4,5,Ewa,IT,7500,2022-11-01,5.0,3
5,6,Filip,HR,4200,2020-08-14,3.5,5
7,8,Henryk,IT,6900,2021-06-18,NaN,6
8,9,Irena,HR,3500,2017-09-23,4.1,5
10,11,Kasia,IT,7200,2020-04-11,5.0,5
11,12,Leszek,HR,4100,2018-11-28,4.3,6
13,14,Norbert,IT,6800,2019-03-19,NaN,7
14,15,Olga,HR,3900,2021-10-08,4.8,4
16,17,Renata,IT,4700,2018-08-31,4.4,6
17,18,Sławek,HR,6100,2022-02-14,4.9,6
19,20,Urszula,IT,5400,2021-09-20,3.8,7
20,3,Celina,HR,3800,2021-01-10,NaN,6
22,12,Leszek,HR,4100,2018-11-28,4.3,6
23,18,Sławek,HR,6100,2022-02-14,4.9,6
24,5,Ewa,IT,7500,2022-11-01,5.0,3
26,22,Xawery,IT,5000,2022-05-20,NaN,6
27,23,Yvonne,HR,NaN,NaN,4.9,6
29,25,Agata,IT,6600,2019-08-03,4.1,5

In [48]:
# 2. Imiona zawierające literę 'a' (case insensitive)
df_str[df_str['imie'].str.contains('a', case=False)]

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna,dlugosc_imienia
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5,4
1,2,Bartek,IT,6200,2019-07-22,3.8,6
2,3,Celina,HR,3800,2021-01-10,NaN,6
3,4,Darek,Sprzedaz,5100,2018-05-30,4.2,5
4,5,Ewa,IT,7500,2022-11-01,5.0,3
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7,5
8,9,Irena,HR,3500,2017-09-23,4.1,5
9,10,Jan,Sprzedaz,4800,2023-02-07,3.9,3
10,11,Kasia,IT,7200,2020-04-11,5.0,5
12,13,Marta,Sprzedaz,5500,2022-07-15,3.6,5
14,15,Olga,HR,3900,2021-10-08,4.8,4
16,17,Renata,IT,4700,2018-08-31,4.4,6
17,18,Sławek,HR,6100,2022-02-14,4.9,6
18,19,Teresa,Sprzedaz,3800,2019-05-07,NaN,6
19,20,Urszula,IT,5400,2021-09-20,3.8,7
20,3,Celina,HR,3800,2021-01-10,NaN,6
21,7,Gosia,Sprzedaz,5800,2019-12-05,4.7,5
23,18,Sławek,HR,6100,2022-02-14,4.9,6
24,5,Ewa,IT,7500,2022-11-01,5.0,3
25,21,Wanda,Sprzedaz,brak,2023-01-15,4.6,5
26,22,Xawery,IT,5000,2022-05-20,NaN,6
29,25,Agata,IT,6600,2019-08-03,4.1,5

In [49]:
# 3. Imiona kończące się na 'a'
df_str[df_str['imie'].str.contains('a$', regex=True)]

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna,dlugosc_imienia
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5,4
2,3,Celina,HR,3800,2021-01-10,NaN,6
4,5,Ewa,IT,7500,2022-11-01,5.0,3
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7,5
8,9,Irena,HR,3500,2017-09-23,4.1,5
10,11,Kasia,IT,7200,2020-04-11,5.0,5
12,13,Marta,Sprzedaz,5500,2022-07-15,3.6,5
14,15,Olga,HR,3900,2021-10-08,4.8,4
16,17,Renata,IT,4700,2018-08-31,4.4,6
18,19,Teresa,Sprzedaz,3800,2019-05-07,NaN,6
19,20,Urszula,IT,5400,2021-09-20,3.8,7
20,3,Celina,HR,3800,2021-01-10,NaN,6
21,7,Gosia,Sprzedaz,5800,2019-12-05,4.7,5
24,5,Ewa,IT,7500,2022-11-01,5.0,3
25,21,Wanda,Sprzedaz,brak,2023-01-15,4.6,5
29,25,Agata,IT,6600,2019-08-03,4.1,5